<?php
/**
 * Created by PhpStorm.
 * User: dima
 * Date: 9/10/2017
 * Time: 7:42 PM
 */

namespace app\models\Users;
use app\models\Abstractive\Complex\ItemsPack;
use app\models\ObjFactory;


/**
 * Class UsersPack
 *
 * @property integer user_id
 * @property string name
 * @property string avatar
 * @property string avatar_low
 * @property string phone
 * @property string email
 * @property string country
 * @property string city
 * @property string address
 * @property string postal_code
 * @property string updated
 * @property string password
 * @property FavouritesPack favourites
 * @property OrdersPack orders
 * @method UsersPack flush
 */
class UsersPack extends ItemsPack
{

    protected static $_primaryKey = ['user_id'];

    protected static $_tableName = 'users';

    /**
     * @param $name
     * @param $value
     * @return bool
     */
    protected function isProperType($name, $value)
    {
        if(($name === 'orders' && $value instanceof OrdersPack)
            || ($name === 'favourites' && $value instanceof FavouritesPack)){
            return parent::isProperType($name, $value);
        }
        return false;
    }

    public function __set($name, $value)
    {
        if ($name === 'password')
        {
            $value = ObjFactory::webUser()->encryptPassword($value);
        }
        return parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    protected function initializeReferences()
    {
        $this->_references['orders'] = new OrdersPack();
        $this->_references['favourites'] = new FavouriteListPack();
        return parent::initializeReferences();
    }

    protected $_fields = [
        'user_id' => null,
        'name' => null,
        'avatar' => null,
        'avatar_low' => null,
        'phone' => null,
        'email' => null,
        'country' => null,
        'city' => null,
        'address' => null,
        'postal_code' => null,
        'password' => null,
        'updated' => null,
    ];

    protected $_references = [
        'orders' => null,
        'favourites' => null
    ];

    protected $_mandatory = [
        'name' => true,
        'phone' => true,
        'email' => true,
        'password' => true
    ];
}