<?php

namespace app\models\ProductsImages;

use app\models\Abstractive\Complex\ItemsDelete;
use Yii;

class ProductsImagesDelete extends ItemsDelete
{
    public function __construct($ids)
    {
        $this->_tableName = ProductsImagesPack::getTableName();
        $this->_idName = ProductsImagesPack::getPrimaryKey();
        parent::__construct($ids);
    }

    /**
     * delete image from disk
     *
     * @param $imagePath
     * @return bool
     */
    private function _deleteImage($imagePath)
    {
        $image = yii::getAlias('@app').'/web'.$imagePath;

        if (file_exists($image))
        {
            return unlink($image);
        }
        return false;
    }

    public function delete()
    {
        $offset = 0;
        $step = 100;
        while ($array = array_slice($this->_ids['products_image_id'], $offset, $offset+$step))
        {
            $product = new ProductsImages();
            $items = $product->getItemsByIds(['products_image_id' => $array, 'product_id' => $this->_ids['product_id']]);

            for($items->first();$items->current();$items->next())
            {
                $this->_deleteImage($items->image_thumb);
                $this->_deleteImage($items->image_low);
                $this->_deleteImage($items->image_high);
            }
            $offset += $step;
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}