<?php
/**
 * Created by PhpStorm.
 * User: dima
 * Date: 6/5/2017
 * Time: 5:34 PM
 */

namespace app\models\ProductsImages;
use app\models\Abstractive\Complex\ModelAccessor;

/**
 * @method ProductsImagesPack getItemsByIds($ids)
 *
 * @var ProductsImagesPack _items
 *
 */
class ProductsImages extends ModelAccessor
{
    protected function initialize()
    {
        $this->_items = new ProductsImagesPack();
    }

    public function orderBy($query)
    {
        $query->orderBy("main desc, product_id desc");
        return $query;
        //return parent::orderBy($query); // TODO: Change the autogenerated stub
    }
}